/**
 * Auto-generated version header
 * DO NOT EDIT - generated by CMake pre-build script
 * 
 * Version format: v{MAJOR}.{MINOR}.{BUILD}
 * - MAJOR/MINOR: defined in config.h (semantic versioning)
 * - BUILD: auto-incremented, resets to 0 when MAJOR/MINOR change
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR               0
#define VERSION_MINOR               1
#define BUILD_NUMBER                102
#define BUILD_TIMESTAMP             "2026-06-06 10:33:27"
#define VERSION_STRING              "v0.1.102"

// Full version identifier for logs and UI
#define APP_FULL_VERSION            VERSION_STRING " (" BUILD_TIMESTAMP ")"

#endif // VERSION_H
